lastfm/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :tags, only: [:index, :create, :show, :update, :destroy]

  resources :users, only: [:index, :create, :show, :update, :destroy] do
    resources :playlists , only: [:index]
  end

  resources :playlists, only: [:index, :create, :show, :update, :destroy] do
    resources :tracks , only: [:index, :create, :destroy]

    get 'shares', to: 'playlist_shares#index'
    post 'shares', to: 'playlist_shares#create'
    delete 'shares/:id', to: 'playlist_shares#destroy'
  end

  resources :tracks, only: [:index, :create, :show, :update, :destroy] do
    resources :tags, only: [:index, :create, :destroy]
  end

end

lastfm/app/models/track.rb
class Track < ActiveRecord::Base
    has_and_belongs_to_many :tags

    has_many :playlist_tracks, :dependent => :destroy
    has_many :playlists, :through => :playlist_tracks, :source => :playlist

    validates :title, presence: true
    validates :artist_name, presence: true
end

lastfm/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :set_playlist, only: [:create, :destroy, :index]
  before_action :authenticate, except: [:index, :show]
  skip_before_action :verify_authenticity_token
  wrap_parameters format: [:json]

  # GET (/playlists/:playlist_id)/tracks
  # GET (/playlists/:playlist_id)/tracks.json
  def index
    @tracks = Track.all
    if @playlist
      # @tracks = Track.includes(:playlists).where(playlists: {id: @playlist.id})
      respond_to do |format|
        format.html { render :index_playlist}
        format.json { render :index_playlist}
      end
    end
  end

  def index_playlist
    respond_to do |format|
      format.html { render html: @playlist.playlist_tracks}
      format.json { render json: @playlist.playlist_tracks, status: :ok }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # POST (/playlists/:playlist_id)/tracks
  # POST (/playlists/:playlist_id)/tracks.json
  def create
    if @playlist
      if track_params[:id]
        add_track_to_playlist
      else
        respond_to do |format|
          format.html { redirect_to @playlist, notice: 'Failed to add the track to the playlist. You must specify id of the track.' }
          format.json { render json: @playlist, status: :unprocessable_entity }
        end
      end
    else
      create_new_track
    end
  end

  def add_track_to_playlist
    @playlist.playlist_tracks.create(order: @playlist.playlist_tracks.count + 1, track_id: track_params[:id])
    @track = Track.find(track_params[:id])
    respond_to do |format|
      format.html { redirect_to @playlist, notice: 'Track was successfully added to the playlist.' }
      format.json { render :show, status: :ok, location: @track }
    end
  end

  def create_new_track
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    if !@track
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Track was not found.' }
        format.json { head :not_found }
      end
    else
      respond_to do |format|
        if @track.update(track_params)
          format.html { redirect_to @track, notice: 'Track was successfully updated.' }
          format.json { render :show, status: :ok, location: @track }
        else
          format.html { render :edit }
          format.json { render json: @track.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE (/playlists/:playlist_id)/tracks/1
  # DELETE (/playlists/:playlist_id)/tracks/1.json
  def destroy
    if !@track
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Track was not found.' }
        format.json { head :not_found }
      end
    else
      if @playlist
        @playlist.tracks.delete(@track)
      else
        @track.destroy
      end

      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      if Track.exists?(params[:id])
        @track = Track.find(params[:id])
      end
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        if @playlist
          User.exists?(:username => name) && User.find_by_username(name).password == password &&
          (User.find_by_username(name).playlists.exists?(@playlist) ||
          User.find_by_username(name).playlist_shares.exists?(@playlist))
        else
          User.exists?(:username => name) && User.find_by_username(name).password == password
        end
      end
    end

    def set_playlist
      if params[:playlist_id] 
        @playlist = Playlist.find(params[:playlist_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:id, :title, :artist_name)
    end
end

lastfm/app/helpers/tracks_helper.rb
module TracksHelper
end

lastfm/app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lastfm/app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

lastfm/app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.artist_name %></td>
        <td> - <%= track.title %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

lastfm/app/views/tracks/index_playlist.html.erb
<h1>Listing tracks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist.playlist_tracks.each do |playlist_track| %>
      <tr>
        <td><%= playlist_track.order %>.</td>
        <td><%= playlist_track.track.artist_name %></td>
        <td> - <%= playlist_track.track.title %></td>
        <td><%= link_to 'Show', playlist_track.track %></td>
        <td><%= link_to 'Destroy', playlist_track.track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

lastfm/app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

lastfm/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

ID: <%= @track.id %> <BR>
Artist: <%= @track.artist_name %> <BR>
Title: <%= @track.title %> <BR>
<%= link_to 'Back', tracks_path %>