lastfm/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :tags, only: [:index, :create, :show, :update, :destroy]

  resources :users, only: [:index, :create, :show, :update, :destroy] do
    resources :playlists , only: [:index]
  end

  resources :playlists, only: [:index, :create, :show, :update, :destroy] do
    resources :tracks , only: [:index, :create, :destroy]

    get 'shares', to: 'playlist_shares#index'
    post 'shares', to: 'playlist_shares#create'
    delete 'shares/:id', to: 'playlist_shares#destroy'
  end

  resources :tracks, only: [:index, :create, :show, :update, :destroy] do
    resources :tags, only: [:index, :create, :destroy]
  end

end

lastfm/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_and_belongs_to_many :tracks

    validates :name, presence: true
end

lastfm/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :set_track, only: [:create, :destroy, :index]
  before_action :authenticate, except: [:index, :show]
  skip_before_action :verify_authenticity_token
  # wrap_parameters format: [:json]


  # GET (tracks/:track_id)/tags
  # GET (tracks/:track_id)/tags.json
  def index
    @tags = Tag.all
    if @track
      @tags = Tag.includes(:tracks).where(tracks: {id: @track.id})
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # POST (tracks/:track_id)/tags
  # POST (tracks/track_id)/tags.json
  def create
    if @track
      if tag_params[:id]
        add_tag_to_track
      else
        respond_to do |format|
          format.html { redirect_to @track, notice: 'Failed to add the tag to the track. You must specify id of the tag.' }
          format.json { render json: @track, status: :unprocessable_entity }
        end
      end
    else
      create_new_tag
    end
  end

  def add_tag_to_track
    @tag = Tag.find_by id: tag_params[:id]
    @track.tags << @tag
    respond_to do |format|
      format.html { redirect_to @playlist, notice: 'Track was successfully added to the playlist.' }
      format.json { render :show, status: :ok, location: @tag }
    end
  end

  def create_new_tag
    @tag = Tag.find_by name: tag_params[:name]
    if @tag
      respond_to do |format|
          format.html { redirect_to @tag, notice: 'Tag already exists.' }
          format.json { render :show, status: :found, location: @tag }
      end
    else
      @tag = Tag.new(tag_params)
      respond_to do |format|
        if @tag.save
          format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
          format.json { render :show, status: :created, location: @tag }
        else
          format.html { render :new }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    if !@tag
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Tag was not found.' }
        format.json { head :not_found }
      end
    else
      respond_to do |format|
        if @tag.update(tag_params)
          format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
          format.json { render :show, status: :ok, location: @tag }
        else
          format.html { render :edit }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE (tracks/:track_id)/tags/1
  # DELETE (tracks/:track_id)/tags/1.json
  def destroy
    if !@tag
      respond_to do |format|
        format.html { redirect_to tracks_url, notice: 'Tag was not found.' }
        format.json { head :not_found }
      end
    else
      if @track
        @track.tags.delete(@tag)
      else 
        @tag.destroy
      end

      respond_to do |format|
        format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      if Tag.exists?(params[:id])
        @tag = Tag.find(params[:id])
      end
    end

    def set_track
      if params[:track_id] 
        @track = Track.find(params[:track_id])
      end
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        User.exists?(:username => name) && User.find_by(username: name).password == password
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:id, :name)
    end
end

lastfm/app/helpers/tags_helper.rb
module TagsHelper
end

lastfm/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lastfm/app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

lastfm/app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%=tag.name%></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

lastfm/app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

lastfm/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<%= @tag.name %> <BR>
<%= link_to 'Back', tags_path %>