lastfm/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :tags, only: [:index, :create, :show, :update, :destroy]

  resources :users, only: [:index, :create, :show, :update, :destroy] do
    resources :playlists , only: [:index]
  end

  resources :playlists, only: [:index, :create, :show, :update, :destroy] do
    resources :tracks , only: [:index, :create, :destroy]

    get 'shares', to: 'playlist_shares#index'
    post 'shares', to: 'playlist_shares#create'
    delete 'shares/:id', to: 'playlist_shares#destroy'
  end

  resources :tracks, only: [:index, :create, :show, :update, :destroy] do
    resources :tags, only: [:index, :create, :destroy]
  end

end

lastfm/app/models/playlist.rb
class Playlist < ActiveRecord::Base
    belongs_to :user
    
    # has_many :playlist_shares, :dependent => :destroy
    # has_many :user_shares, :through => :playlist_shares, :source => :user
    has_many :user_shares, :class_name => 'PlaylistShare', :foreign_key => 'playlist_id', :dependent => :destroy

    has_many :playlist_tracks, :dependent => :destroy
    has_many :tracks, :through => :playlist_tracks, :source => :track

    validates :title, presence: true
    validates :user_id, presence: true
end

lastfm/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  wrap_parameters format: [:json]
  before_action :authenticate, except: [:index, :show]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all

    # playlists = []
    # @playlists.each do |p|
    #   newp = {
    #     title:p.title,
    #     desc:p.description,
    #     owner:{
    #       id:p.user.id,
    #       username:p.user.username
    #     }
    #   }
    #   playlists.push(newp)
    # end

    # render :json => {playlist:playlists}

  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show

  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_update_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:title, :user_id, :description)
    end

    def playlist_update_params
      params.require(:playlist).permit(:title, :description)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        if @playlist
          User.exists?(:username => name) &&
          User.find_by_username(name).password == password &&
          User.find_by_username(name).playlists.exists?(@playlist)
        else
          User.exists?(:username => name) &&
          User.find_by_username(name).password == password &&
          User.find_by_username(name).id == params[:user_id]

        end
      end
    end
end

lastfm/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

lastfm/app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lastfm/app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

lastfm/app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.title %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

lastfm/app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

lastfm/app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<%= @playlist.title %> <BR>
<%= @playlist.description %> <BR>
Tracks: <BR>
<% @playlist.playlist_tracks.each do |playlist_track| %>
  <tr>
    <td><%= playlist_track.order %>.</td>
    <td><%= playlist_track.track.artist_name %> - </td>
    <td><%= playlist_track.track.title %> <br></td>
  </tr>
<% end %>
<br>
<%= link_to 'Back', playlists_path %>